apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      containers:
        - name: gitlab-runner
          image: mrm78/gitlab-runner
          imagePullPolicy: Always
          args: ["run"]
          env:
            - name: CI_SERVER_URL
              value: "https://gitlab.com/"
            - name: REGISTRATION_TOKEN
              value: lskdvlsidjlsdkcsjdhflsidkjfkdmc
            - name: DOCKER_HOST
              value: "tcp://docker:2375"
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: runner-config
              mountPath: /etc/gitlab-runner
      volumes:
        - name: runner-config
          persistentVolumeClaim:
            claimName: runner-config
      nodeSelector:
        x-gitlab-runner: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi